language: elixir
matrix:
  include:
    - otp_release: 20.1
      elixir: 1.7
      env:
        - CHECK_FORMAT=true
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
script:
  - mix docs
  - mix test
  - if [ "$CHECK_FORMAT" == "true" ]; then mix format --check-formatted; fi
  - mix dialyzer
